"""cardtype

Revision ID: 3c2f265c100b
Revises: c35c72e6c022
Create Date: 2021-12-02 16:22:13.880700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c2f265c100b'
down_revision = 'c35c72e6c022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('typ', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'typ')
    # ### end Alembic commands ###
