"""INitiale

Revision ID: c35c72e6c022
Revises: 
Create Date: 2021-12-02 16:21:44.550914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c35c72e6c022'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hall')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hall',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('namn', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
